### ISSUE TITLE
[Feature] Sorting the blog post

### ISSUE THREAD

**Issue by grgprarup** [JankariTech/blog#154]
The feature mentioned in the issue https://github.com/JankariTech/blog/issues/148 is added in PR https://github.com/JankariTech/blog/pull/152.

Now, we have two dates `first published` and the `last updated`.

How can we sort the blogpost?
- only by published date (which is the current behavior)
- sort by last updated and published date

Any suggestions?

**Comment by koebel** [comment]
Good point – I would suggest that for now the sorting should be based on the publishing date. However this should be taken into consideration when we look at improving sorting in https://github.com/JankariTech/blog/issues/129

Since the current modification doesn't break sort, I think we can close this issue and add comments and recommendations relating to this to the issue mentioned above.
